# Ques 1. Create a numpy array with 10 elements of the shape(10,1) using np.random and find out the mean of the elements using basic numpy functions.

In [4]:
import numpy as np
import sys
import time
a=np.random.random((10,1))
print(a)
print("Mean is : ",a.mean())

[[0.25038265]
 [0.7193692 ]
 [0.86213472]
 [0.18460237]
 [0.89496448]
 [0.4268551 ]
 [0.63258671]
 [0.51659934]
 [0.35005793]
 [0.60963001]]
Mean is :  0.5447182498224555


# Ques 2. Create a numpy array with 20 elements of the shape(20,1) using np.random find the variance and standard deviation of the elements.

In [4]:
import numpy as np
import sys
import time
a=np.random.randint(0,30,(20,1))
print(a)
print("Variance of array is : ",a.var())
print("Standard Deviation is : ",a.std())

[[ 9]
 [ 1]
 [26]
 [ 3]
 [10]
 [13]
 [19]
 [26]
 [18]
 [16]
 [21]
 [ 3]
 [ 7]
 [18]
 [29]
 [15]
 [26]
 [17]
 [ 5]
 [ 2]]
Variance of array is :  75.15999999999998
Standard Deviation is :  8.669486720677297


# Ques 3. Create a numpy array A of shape(10,20) and B of shape (20,25) using np.random. Print the matrix which is the matrix multiplication of A and B. The shape of the new matrix should be (10,25). Using basic numpy math functions only find the sum of all the elements of the new matrix.

In [3]:
import numpy as np
import sys
import time
a=np.random.randint(0,50,(10,20))
print("\nMatrix A is :\n",a)
b=np.random.randint(0,50,(20,25))
print("\n\nMatrix B is :\n",b)
c=np.matmul(a,b)
print("\n\nMultiplication of Two Matrices is: \n",c)
print("\n\n Sum of elements of new matrix is: ",c.sum())




Matrix A is :
 [[26  3  6  1 49 21 48 46 33 10  1  8 49 15 48  7 12  3 10 49]
 [ 5 16 47 18 18  0 10 19 16 21 10 11  9  0 22 26 17 20 45  9]
 [49 20 34 26 25 49 44 47 18 47 36 40 46 22 41 34 15 30  5 39]
 [36 45 30 18 20 28 44 35 10 28 10 18 17  1 21 10 22 26 39  1]
 [37 43 32 10 44 10 38 25 28 45 48 27 14 37 46  9 37 11 29  9]
 [18  9 49 40 20 45 17 22 33 43 20 11 18 44 37 21 36  4 29  5]
 [24 42  7 43 29 42 43  1 42 28 12 36 46 37 23 44 11 47 36  3]
 [ 8 23  5 45 39 10 16 47 20 13 26 23 39 47  8 40 46  1 15 36]
 [25 23 26 26 13 17 44 39  2  6 49 44 20 38 20 14 43 34 21 43]
 [49 49 16 45 28 22 42 38 30 31 48 31 45 25 13 30 23 16 23 12]]


Matrix B is :
 [[18 46 30 15 15 21 46 27 17  8  4 11 41 21 47 39 30 47 15 20  1 44 11  4
   9]
 [29 24 34  6  2 18 20 29 11 37 35 20 34 36 10 47 43 44  0 10 23 11  7 25
  42]
 [43  7  4 10 47 43 23 47 10 41 28  1 47 46 49  5 46 17 24 42 12  0 40 20
  20]
 [27  6 28 34 46 43  9 29 13 36 16 34 30 10  8 49 49 17 27 42 39  3 39 14
  32]
 [30 16 21 24 22

# Ques4. Create a numpy array A of shape(10,1).Using the basic operations of the numpy array generate an array of shape(10,1) such that each element is the following function applied on each element of A. 
# 
# f(x)=1 / (1 + exp(-x)) 
# Apply this function to each element of A and print the new array holding the value the function returns
# Example:
# 
# a=[a1,a2,a3]   
# n(new array to be printed )=[ f(a1), f(a2), f(a3)]

In [6]:
import numpy as np
import sys
import time
a=np.random.randint(0,100,(10,1))
def function(x):
    y=1/(1+np.exp(-x))
    return y
list=[]
for x in a:
    list.append(function(x))
b=np.array(list)
print(b)

[[0.99999774]
 [1.        ]
 [0.99999386]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]]
